project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - data_cleaning.qmd
    - visualizations.qmd

website:
  title: "OpenKBP Data Visualization"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: data_cleaning.qmd
        text: Limpieza de datos
      - href: visualizations.qmd
        text: Visualizaciones

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true